artifact_location: file:///home/nicolasd/code/nicolasdestrac/OpenClassrooms/Projet_7/mlruns_tune/0
creation_time: 1759659848357
experiment_id: '0'
last_update_time: 1759659848357
lifecycle_stage: active
name: Default
