artifact_uri: file:///home/nicolasd/code/nicolasdestrac/OpenClassrooms/Projet_7/mlruns_tune/868692920072115364/c8afddb7b5cc44c5a336b046780a5c0c/artifacts
end_time: null
entry_point_name: ''
experiment_id: '868692920072115364'
lifecycle_stage: active
run_id: c8afddb7b5cc44c5a336b046780a5c0c
run_name: tune_rf_random
source_name: ''
source_type: 4
source_version: ''
start_time: 1759659848519
status: 1
tags: []
user_id: nicolasd
