artifact_location: file:///home/nicolasd/code/nicolasdestrac/OpenClassrooms/Projet_7/mlruns_tune/868692920072115364
creation_time: 1759659848364
experiment_id: '868692920072115364'
last_update_time: 1759659848364
lifecycle_stage: active
name: tuning_local
